# Plugin specific
name: Tickrate-Changer
version: 1.0.0-SNAPSHOT
description: Tickrate changer API for the modded papermc server
author: Pancake
website: https://tasbattle.mgnet.work

# Implementation specific
main: de.pancake.trc.TickrateChanger
load: POSTWORLD
api-version: 1.17

commands:
    tickrate:
        usage: /tickrate <tickrate>
        description: Updates the tickrate
        aliases: [ticks]