# Plugin specific
name: TAS-Battle-Tickrate-Changer
version: 1.0.0-SNAPSHOT
description: Tickrate changer API for the modded papermc server
author: Pancake
website: https://minecrafttas.com/tas-battle/

# Implementation specific
main: com.minecrafttas.tasbattle.tickratechanger.TickrateChanger
load: POSTWORLD
api-version: 1.19

commands:
    tickrate:
        usage: /tickrate <tickrate>
        description: Updates the tickrate
        aliases: [ticks]
