# Plugin specific
name: TAS-Battle-Gameserver
version: 1.0.0-SNAPSHOT
description: tas battle gameserver plugin
author: Pancake
website: https://minecrafttas.com/tas-battle/

# Implementation specific
main: com.minecrafttas.tasbattle.TASBattleGameserver
load: POSTWORLD
api-version: 1.19

commands:
    tickrate:
        usage: /tickrate <tickrate>
        description: Updates the tickrate
    ffa:
        usage: /ffa <save/load/delete>
        description: FFA commands
    ready:
        usage: /ready <force>
        description: Set yourself to ready
    halt:
        usage: /halt
        description: Halts the server immediately

