# Plugin specific
name: TAS-Battle
version: 1.0.0-SNAPSHOT
description: TAS-Battle plugin
author: Pancake
website: https://minecrafttas.com/tas-battle/

# Implementation specific
main: com.minecrafttas.tasbattle.TASBattle
load: POSTWORLD
api-version: 1.19

commands:
    tickrate:
        usage: /tickrate <tickrate>
        description: Updates the tickrate
    saveffakit:
        usage: /saveffakit <name> <material> <description...>
        description: Saves an ffa kit
    delffakit:
        usage: /delffakit <filename>
        description: Deletes an ffa kit
    loadffakit:
        usage: /loadffakit <filename>
        description: 
