# Plugin specific
name: TAS-Battle-FFA
version: 2.0.0-SNAPSHOT
description: FFA plugin for the TAS Battle server
author: Pancake
website: https://minecrafttas.com/tas-battle/

# Implementation specific
main: com.minecrafttas.tasbattle.ffa.FFA
load: POSTWORLD
api-version: 1.17
depend: ["TAS-Battle-Common", "TAS-Battle-Tickrate-Changer"]
