# Plugin specific
name: TAS-Battle-Common
version: 1.0.0-SNAPSHOT
description: Common TAS Battle Library for all plugins
author: Pancake
website: https://minecrafttas.com/tas-battle/

# Implementation specific
main: com.minecrafttas.tasbattle.common.CommonTASBattle
load: POSTWORLD
api-version: 1.19
